% LM BOUTON CALCIUM IMAGING ANALYSIS
datasetID = '062025_347_r2_correlation_thresh6_0925_newtest';

filepath = ...
    '/Volumes/LM 2P/LM 2P analysis/347/062025/r2/suite2p/plane0/Fall.mat';

load(filepath);  % Loads F, iscell, ops, etc.

[baseDir, ~, ~] = fileparts(filepath);

saveDir = fullfile(baseDir, datasetID);
resultsDir = fullfile(saveDir, 'bouton_analysis_corr_thresh6_newtest');

if ~exist(resultsDir, 'dir')
    mkdir(resultsDir);
end

%% ----- Output Files -----

boutonResultsFile = fullfile( ...
    resultsDir, ...
    sprintf('%s_bouton_analysis_results.csv', datasetID));

dffSelectedFile = fullfile( ...
    resultsDir, ...
    sprintf('%s_normalized_dFF_selected.mat', datasetID));

corrFile = fullfile( ...
    resultsDir, ...
    sprintf('%s_pairwise_correlations.csv', datasetID));

clusterMapFile = fullfile( ...
    resultsDir, ...
    sprintf('%s_cluster_ROI_mapping.csv', datasetID));

eventFramesFile = fullfile( ...
    resultsDir, ...
    sprintf('%s_event_frames.csv', datasetID));

allSnipsFile = fullfile( ...
    resultsDir, ...
    sprintf('%s_all_event_snippets.csv', datasetID));

summaryFile = fullfile( ...
    resultsDir, ...
    sprintf('%s_processing_summary.txt', datasetID));

allVarsFile = fullfile( ...
    resultsDir, ...
    sprintf('%s_analysis_variables.mat', datasetID));


%% ANALYSIS PARAMETERS
minMeanFluorescence = 15;

smoothingKernel = ones(1,5) / 5;

percentileWindowSize = 1800;
percentileValue      = 10;
strideSize           = 30;

frameRate    = 30;
framesBefore = 60;      
framesAfter  = 120;     

correlationThreshold = 0.8;

nTailBins = 10;

gaussianSDMultiplier = 2;
maximumEventThreshold = 6;

filterOrder = 4;
filterCutoff = 0.1;

minEventFrames = 15;
refractorySeconds = 4;


%% Suite2P ROI Selection

numRawROIs = size(F, 1);
origIdx = (1:numRawROIs)';
cellFilter = iscell(:,1) == 1;
F = F(cellFilter, :);
%Fneu = Fneu(cellFilter, :);  %uncomment if doing soma analysis

origIdx = origIdx(cellFilter);
meanFluorescence = mean(F, 2);
validFluorescence = meanFluorescence >= minMeanFluorescence;
F = F(validFluorescence, :);
% Cell-body analysis:
% F_analysis = F - 0.7 * Fneu; %%replace F with F_analysis for soma 
% analysis 
origIdx = origIdx(validFluorescence);


%% SMOOTH FLUORESCENCE TRACES
F = myconv2(F, smoothingKernel);

%%CALCULATE BASELINE AND dF/F

numROIs = size(F,1);
numFrames = size(F,2);

saveddfFcellData = NaN(numROIs, numFrames);
validBaseline = true(numROIs,1);

for i = 1:numROIs

    rawData = F(i,:);

    f0 = runningPercentile( ...
        rawData, ...
        percentileWindowSize, ...
        percentileValue, ...
        strideSize);

    if any(f0 < 1e-6) || any(~isfinite(f0))

        fprintf( ...
            'Original ROI %d (filtered row %d): invalid F0. Excluding.\n', ...
            origIdx(i), i);

        validBaseline(i) = false;
        continue;
    end

    dfF = (rawData - f0) ./ f0;
    dfF(~isfinite(dfF)) = 0;

    saveddfFcellData(i,:) = dfF;

end


% Remove ROIs with invalid baseline estimates
saveddfFcellData = saveddfFcellData(validBaseline,:);
origIdx = origIdx(validBaseline);

numROIs = size(saveddfFcellData,1);

%% TEMPORAL BINNING FOR CORRELATION ANALYSIS
%%correlation analysis should be skipped for the soma data 

if isfield(ops, 'fs')
    binSize = round(ops.fs);
else
    binSize = frameRate;
end

numBins = floor(numFrames / binSize);

if numBins < 1
    error( ...
        'Too few frames (%d) for %d-frame temporal bins.', ...
        numFrames, binSize);
end

framesForBinning = 1:(binSize * numBins);

binned = zeros(numROIs, numBins);

for i = 1:numROIs

    tmp = reshape( ...
        saveddfFcellData(i,framesForBinning), ...
        binSize, ...
        numBins);

    binned(i,:) = mean(tmp,1);

end

R = corrcoef(binned');

adjacencyMatrix = R >= correlationThreshold;

% Remove self-connections
adjacencyMatrix(1:size(adjacencyMatrix,1)+1:end) = false;

n = size(R,1);

[iIdx, jIdx] = find(triu(true(n),1));

corrVals = R(sub2ind([n n], iIdx, jIdx));

corrTable = table( ...
    iIdx, ...
    jIdx, ...
    origIdx(iIdx), ...
    origIdx(jIdx), ...
    corrVals, ...
    'VariableNames', { ...
    'FilteredROI1', ...
    'FilteredROI2', ...
    'OriginalROI1', ...
    'OriginalROI2', ...
    'Correlation'});

writetable(corrTable, corrFile);

G = graph(adjacencyMatrix);

clusterAssignment = conncomp(G);

numClusters = max(clusterAssignment);

groupMap = arrayfun( ...
    @(g) find(clusterAssignment == g), ...
    1:numClusters, ...
    'UniformOutput', false);

fprintf('Independent bouton clusters after correlation grouping: %d\n', ...
    numClusters);

clusterIDColumn = [];
filteredROIColumn = [];
originalROIColumn = [];

for g = 1:numClusters

    members = groupMap{g};

    clusterIDColumn = [ ...
        clusterIDColumn; ...
        repmat(g, numel(members), 1)]; %#ok<AGROW>

    filteredROIColumn = [ ...
        filteredROIColumn; ...
        members(:)]; %#ok<AGROW>

    originalROIColumn = [ ...
        originalROIColumn; ...
        origIdx(members)]; %#ok<AGROW>

end

clusterMapTable = table( ...
    clusterIDColumn, ...
    filteredROIColumn, ...
    originalROIColumn, ...
    'VariableNames', { ...
    'ClusterID', ...
    'FilteredROI', ...
    'OriginalSuite2pROI'});

writetable(clusterMapTable, clusterMapFile);

dfF_clustered = zeros(numClusters, numFrames);

for g = 1:numClusters

    members = groupMap{g};

    dfF_clustered(g,:) = ...
        mean(saveddfFcellData(members,:), 1);

end

clusterThresholds  = NaN(numClusters,1);
clusterGaussParams = NaN(numClusters,2);  % [mode, sigma]

numEventsPerCluster = zeros(numClusters,1);

dfFEventSnippets = cell(numClusters,1);
allEventFrames   = cell(numClusters,1);

% Processing summary counters
skipNoNegTail      = 0;
skipNotEnoughBins  = 0;
skipBadFit         = 0;
skipInvalidSigma   = 0;
skipHighThreshold  = 0;
skipNoEvents       = 0;


%% ----- Butterworth Filter Coefficients -----

[b,a] = butter(filterOrder, filterCutoff, 'low');

%%GAUSSIAN THRESHOLDING AND EVENT DETECTION

for k = 1:numClusters

    trace = dfF_clustered(k,:);
    [fKDE, xi] = ksdensity(trace);
    [~, idxMode] = max(fKDE);
    modeVal = xi(idxMode);
    negTail = trace(trace < modeVal);
    if isempty(negTail)
        skipNoNegTail = skipNoNegTail + 1;
        fprintf( ...
            'Cluster %d: no negative-tail data. Excluding.\n', ...
            k);
        continue;
    end
    minTail = min(negTail);
    tailBinEdges = linspace( ...
        minTail, ...
        modeVal, ...
        nTailBins + 1);
    if numel(unique(tailBinEdges)) < 2
        skipNotEnoughBins = skipNotEnoughBins + 1;
        fprintf( ...
            'Cluster %d: insufficient negative-tail range. Excluding.\n', ...
            k);
        continue;
    end
    tailCounts = histcounts(negTail, tailBinEdges);
    if sum(tailCounts) == 0
        skipNotEnoughBins = skipNotEnoughBins + 1;
        continue;
    end
    tailPDF = tailCounts ./ sum(tailCounts);
    tailCenters = ...
        0.5 * (tailBinEdges(1:end-1) + tailBinEdges(2:end));
    xTail = tailCenters - modeVal;
    xTail = xTail(:);
    y = tailPDF(:);

    %% ----- Negative-Tail Gaussian Fit -----
    initialAmplitude = max(y);
    initialSigma = ...
        (modeVal - minTail) / 2;
    gaussianFunction = ...
        @(p,x) p(1) .* exp(-(x.^2) ./ (2*p(2)^2));
    initialParameters = ...
        [initialAmplitude, initialSigma];
    try
        fitParameters = nlinfit( ...
            xTail, ...
            y, ...
            gaussianFunction, ...
            initialParameters);
    catch ME
        skipBadFit = skipBadFit + 1;
        fprintf( ...
            'Cluster %d: Gaussian fit failed: %s\n', ...
            k, ME.message);
        continue;
    end
    sigmaFit = fitParameters(2);
    if ~isfinite(sigmaFit) || sigmaFit <= 0
        skipInvalidSigma = skipInvalidSigma + 1;
        fprintf( ...
            'Cluster %d: invalid Gaussian sigma. Excluding.\n', ...
            k);
        continue;
    end


    %% ----- Event Detection Threshold -----

    clusterGaussParams(k,:) = ...
        [modeVal, sigmaFit];
    clusterThresholds(k) = ...
        modeVal + gaussianSDMultiplier * sigmaFit;
    if clusterThresholds(k) > maximumEventThreshold
        skipHighThreshold = skipHighThreshold + 1;
        fprintf( ...
            'Cluster %d: threshold %.2f > %.2f. Excluding.\n', ...
            k, ...
            clusterThresholds(k), ...
            maximumEventThreshold);
        clusterThresholds(k) = NaN;
        continue;
    end

    %%LOW-PASS FILTER
    filteredTrace = ...
        filtfilt(b, a, double(trace));


    %% DETECT CONTIGUOUS ABOVE-THRESHOLD EVENTS
    aboveThreshold = ...
        filteredTrace > clusterThresholds(k);
    CC = bwconncomp(aboveThreshold);
    candidateOnsets = [];
    candidateEnds   = [];
    for r = 1:CC.NumObjects
        runLength = ...
            numel(CC.PixelIdxList{r});
        if runLength >= minEventFrames
            candidateOnsets(end+1) = ...
                CC.PixelIdxList{r}(1); %#ok<AGROW>
            candidateEnds(end+1) = ...
                CC.PixelIdxList{r}(end); %#ok<AGROW>
        end

    end

    [candidateOnsets, sortIdx] = ...
        sort(candidateOnsets);

    candidateEnds = ...
        candidateEnds(sortIdx);


    %% APPLY FOUR-SECOND REFRACTORY PERIOD

    validOnsets = [];
    validEnds   = [];
    if ~isempty(candidateOnsets)
        validOnsets = candidateOnsets(1);
        validEnds   = candidateEnds(1);
        for j = 2:numel(candidateOnsets)
            if ...
                candidateOnsets(j) - validOnsets(end) ...
                >= refractorySeconds * frameRate
                validOnsets(end+1) = ...
                    candidateOnsets(j); %#ok<AGROW>
                validEnds(end+1) = ...
                    candidateEnds(j); %#ok<AGROW>
            end

        end

    end


    %%EXCLUDE EVENTS NEAR RECORDING BOUNDARIES

    keepMask = ...
        validOnsets > framesBefore & ...
        validOnsets + framesAfter <= numFrames;
    validOnsets = validOnsets(keepMask);
    validEnds   = validEnds(keepMask);
    numEvents = numel(validOnsets);
    numEventsPerCluster(k) = numEvents;
    if numEvents == 0
        skipNoEvents = skipNoEvents + 1;
        allEventFrames{k} = [];
        continue;
    end


    %% EXTRACT EVENT-ALIGNED dF/F TRACES
    snippetLength = ...
        framesBefore + framesAfter + 1;
    eventSnippets = ...
        zeros(numEvents, snippetLength);
    for e = 1:numEvents
        idxStart = ...
            validOnsets(e) - framesBefore;
        idxEnd = ...
            validOnsets(e) + framesAfter;
        eventSnippets(e,:) = ...
            trace(idxStart:idxEnd);
    end
    dfFEventSnippets{k} = eventSnippets;
    allEventFrames{k} = ...
        [validOnsets(:), validEnds(:)];

end

selectedClusters = find( ...
    numEventsPerCluster > 0 & ...
    isfinite(clusterThresholds));

numSelectedClusters = numel(selectedClusters);

dfF_selected = ...
    dfF_clustered(selectedClusters,:);

save( ...
    dffSelectedFile, ...
    'dfF_selected', ...
    'selectedClusters');

fprintf( ...
    'Selected %d bouton clusters with detected events.\n', ...
    numSelectedClusters);


%% EVENT METRICS
meanAmplitudePerCluster   = NaN(numSelectedClusters,1);
eventFrequencyPerCluster  = NaN(numSelectedClusters,1);
AUCPerSelectedEvents      = NaN(numSelectedClusters,1);
AUCWholeTracePerCluster   = NaN(numSelectedClusters,1);

meanEventDurationPerCluster = NaN(numSelectedClusters,1);
meanRiseTimePerCluster      = NaN(numSelectedClusters,1);
meanDecayTimePerCluster     = NaN(numSelectedClusters,1);


gaussianPeak = ...
    clusterGaussParams(selectedClusters,1);

gaussianSD = ...
    clusterGaussParams(selectedClusters,2);

totalRecordingTime = ...
    numFrames / frameRate;
eventTime = ...
    (-framesBefore:framesAfter) / frameRate;
postIndices = ...
    (framesBefore+1):(framesBefore+framesAfter+1);
positiveTimeIndices = ...
    eventTime >= 0;
allEventSnipsTable = [];
for idx = 1:numSelectedClusters
    k = selectedClusters(idx);
    eventSnippets = ...
        dfFEventSnippets{k};
    framesOnOff = ...
        allEventFrames{k};
    numEvents = ...
        size(eventSnippets,1);
    localAmplitudes = NaN(numEvents,1);
    localAUCs       = NaN(numEvents,1);
    durations       = NaN(numEvents,1);
    riseTimes       = NaN(numEvents,1);
    decayTimes      = NaN(numEvents,1);
    baseline = gaussianPeak(idx);
    for e = 1:numEvents
        trace = eventSnippets(e,:);
        row = ...
            [k, e, trace];
        allEventSnipsTable = ...
            [allEventSnipsTable; row]; %#ok<AGROW>

        onsetFrame = framesOnOff(e,1);
        endFrame   = framesOnOff(e,2);
        durations(e) = ...
            (endFrame - onsetFrame) / frameRate;

        [peakValue, peakIndex] = ...
            max(trace(postIndices));

        absolutePeakIndex = ...
            postIndices(peakIndex);

        localAmplitudes(e) = ...
            peakValue - baseline;

        localAUCs(e) = ...
            trapz( ...
            eventTime(positiveTimeIndices), ...
            trace(positiveTimeIndices));

        threshold80 = ...
            baseline + ...
            0.8 * (peakValue - baseline);

        riseSearchRange = ...
            (framesBefore+1):absolutePeakIndex;

        riseCrossing = find( ...
            trace(riseSearchRange) >= threshold80, ...
            1, ...
            'first');

        if ~isempty(riseCrossing)

            riseTimes(e) = ...
                (riseCrossing - 1) / frameRate;

        end

        decaySearchRange = ...
            absolutePeakIndex:(framesBefore+framesAfter+1);

        decayCrossing = find( ...
            trace(decaySearchRange) <= threshold80, ...
            1, ...
            'first');

        if ~isempty(decayCrossing)

            absoluteDecayIndex = ...
                decaySearchRange(decayCrossing);

            decayTimes(e) = ...
                (absoluteDecayIndex - absolutePeakIndex) ...
                / frameRate;

        end

    end

    meanAmplitudePerCluster(idx) = ...
        mean(localAmplitudes, 'omitnan');

    eventFrequencyPerCluster(idx) = ...
        numEvents / totalRecordingTime;

    AUCPerSelectedEvents(idx) = ...
        mean(localAUCs, 'omitnan');

    meanEventDurationPerCluster(idx) = ...
        mean(durations, 'omitnan');

    meanRiseTimePerCluster(idx) = ...
        mean(riseTimes, 'omitnan');

    meanDecayTimePerCluster(idx) = ...
        mean(decayTimes, 'omitnan');

    fullTime = ...
        (0:numFrames-1) / frameRate;

    AUCWholeTracePerCluster(idx) = ...
        trapz( ...
        fullTime, ...
        dfF_selected(idx,:));

end

amplitudeAverageTrace = ...
    NaN(numSelectedClusters,1);

AUCAverageTrace = ...
    NaN(numSelectedClusters,1);

for idx = 1:numSelectedClusters

    k = selectedClusters(idx);

    eventSnippets = ...
        dfFEventSnippets{k};

    meanTrace = ...
        mean(eventSnippets,1);

    peakValue = ...
        max(meanTrace);

    baseline = ...
        gaussianPeak(idx);

    amplitudeAverageTrace(idx) = ...
        peakValue - baseline;
    AUCAverageTrace(idx) = ...
        trapz( ...
        eventTime(positiveTimeIndices), ...
        meanTrace(positiveTimeIndices));

end


resultsTable = table( ...
    selectedClusters, ...
    meanAmplitudePerCluster, ...
    eventFrequencyPerCluster, ...
    AUCPerSelectedEvents, ...
    AUCWholeTracePerCluster, ...
    numEventsPerCluster(selectedClusters), ...
    clusterThresholds(selectedClusters), ...
    amplitudeAverageTrace, ...
    AUCAverageTrace, ...
    gaussianPeak, ...
    gaussianSD, ...
    meanEventDurationPerCluster, ...
    meanRiseTimePerCluster, ...
    meanDecayTimePerCluster, ...
    'VariableNames', { ...
    'ClusterID', ...
    'MeanAmplitude', ...
    'EventFrequency_Hz', ...
    'MeanEventAUC', ...
    'WholeTraceAUC', ...
    'NumEvents', ...
    'EventThreshold', ...
    'AmplitudeAverageTrace', ...
    'AUCAverageTrace', ...
    'GaussianMode', ...
    'GaussianSD', ...
    'MeanEventDuration_s', ...
    'MeanRiseTime_s', ...
    'MeanDecayTime_s'});

writetable(resultsTable, boutonResultsFile);

fprintf( ...
    'Saved bouton analysis results to %s\n', ...
    boutonResultsFile);

writematrix( ...
    allEventSnipsTable, ...
    allSnipsFile);

fprintf( ...
    'Saved event snippets to %s\n', ...
    allSnipsFile);

eventFramesTable = [];

for idx = 1:numSelectedClusters

    k = selectedClusters(idx);

    events = allEventFrames{k};

    if isempty(events)
        continue;
    end

    temp = [ ...
        repmat(k, size(events,1), 1), ...
        (1:size(events,1))', ...
        events];

    eventFramesTable = ...
        [eventFramesTable; temp]; %#ok<AGROW>

end


eventFramesTable = array2table( ...
    eventFramesTable, ...
    'VariableNames', { ...
    'ClusterID', ...
    'EventNumber', ...
    'OnsetFrame', ...
    'EndFrame'});

writetable(eventFramesTable, eventFramesFile);

fid = fopen(summaryFile, 'w');

fprintf(fid, '===== Bouton Processing Summary =====\n\n');

fprintf(fid, ...
    'Raw Suite2p ROIs:                         %d\n', ...
    numRawROIs);

fprintf(fid, ...
    'ROIs after fluorescence/F0 filtering:     %d\n', ...
    numROIs);

fprintf(fid, ...
    'Correlation threshold:                    %.2f\n', ...
    correlationThreshold);

fprintf(fid, ...
    'Independent correlation clusters:         %d\n', ...
    numClusters);

fprintf(fid, ...
    'Selected clusters with detected events:   %d\n', ...
    numSelectedClusters);

fprintf(fid, ...
    'Skipped (no negative tail):               %d\n', ...
    skipNoNegTail);

fprintf(fid, ...
    'Skipped (insufficient negative-tail bins):%d\n', ...
    skipNotEnoughBins);

fprintf(fid, ...
    'Skipped (Gaussian fit failure):           %d\n', ...
    skipBadFit);

fprintf(fid, ...
    'Skipped (invalid Gaussian sigma):         %d\n', ...
    skipInvalidSigma);

fprintf(fid, ...
    'Skipped (event threshold > %.1f):          %d\n', ...
    maximumEventThreshold, ...
    skipHighThreshold);

fprintf(fid, ...
    'Excluded (zero valid events):             %d\n', ...
    skipNoEvents);

fclose(fid);

fprintf( ...
    'Saved processing summary to %s\n', ...
    summaryFile);

save( ...
    allVarsFile, ...
    'origIdx', ...
    'R', ...
    'clusterAssignment', ...
    'groupMap', ...
    'dfF_clustered', ...
    'dfF_selected', ...
    'selectedClusters', ...
    'clusterThresholds', ...
    'clusterGaussParams', ...
    'numEventsPerCluster', ...
    'allEventFrames', ...
    'dfFEventSnippets', ...
    'resultsTable');

fprintf( ...
    'Saved analysis variables to %s\n', ...
    allVarsFile);

fprintf('\nBouton analysis complete.\n');